spring.application.name=receiptserver
spring.datasource.url=jdbc:postgresql://ep-tiny-leaf-alit33cx-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KF3PgUb4McSx

spring.thymeleaf.cache=false

server.port=8080
